name: Build and Deploy a MERN stack application

on:
    workflow_dispatch:
  

env:
    DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER}}
    DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD}}
    VERSION: ${{ github.sha }}

jobs:
    build-and-push:
        name: Build and Push Docker Images
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Login to DockerHub
          run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin

        - name: Build and push Frontend Image
          run: |
            cd ./mern/frontend
            docker build -t $DOCKERHUB_USER/mern-frontend:$VERSION .
            docker push $DOCKERHUB_USER/mern-frontend:$VERSION

        - name: Build and push Backend Image
          run: |
            cd ./mern/backend
            docker build -t $DOCKERHUB_USER/mern-backend:$VERSION .
            docker push $DOCKERHUB_USER/mern-backend:$VERSION
            